### GET all users

GET http://localhost:3003/api/users

### GET all blogs

GET http://localhost:3003/api/blogs

### POST user

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "johnd",
  "name": "John Doe",
  "password": "johnrocks"
}

### POST a blog

POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kIiwiaWQiOiI1ZWY0NTU0MGRhM2E4OTZmNTk2Zjc0NmUiLCJpYXQiOjE1OTM0MjA2MTh9.8hEb3qF08ncQp9D8_mif6Erbr4lVAFPtbboXBGg4C2c

{
  "title": "Beautiful indeed",
  "author": "Charles XVI",
  "url": "http://tomhanks.com",
  "likes": 421
}

### DELETE a blog
DELETE http://localhost:3003/api/blogs/5ef4622536e8e90fe1b75400
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImpvaG5kIiwiaWQiOiI1ZWY0NTU0MGRhM2E4OTZmNTk2Zjc0NmUiLCJpYXQiOjE1OTMwNzQxODR9.gA3KfH1RfVV1b2nUltX6WGXLgxC_O6UN8Ny8nrVONNc

### Login user

POST http://localhost:3003/api/login
Content-Type: application/json

{
  "username": "johnd",
  "password": "johnrocks"
}

### Get comments
GET http://localhost:3003/api/blogs/5f3b84eefbc3af3e39e089b6/comments

### POST comment
POST http://localhost:3003/api/blogs/5f3b84eefbc3af3e39e089b6/comments
Content-Type: application/json

{
  "comment": "Returns new?"
}