### POST a blog

POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testing the refactored app",
  "author": "Johan Lindkvist",
  "url": "http://yes.com",
  "likes": 109
}

### GET all blogs

GET http://localhost:3003/api/blogs

### POST user

POST http://localhost:3003/api/users
Content-Type: application/json

{
  "username": "johnd",
  "name": "John Doe",
  "password": "johnrocks"
}

### GET all users
GET http://localhost:3003/api/users