POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "Testing the refactored app",
  "author": "Johan Lindkvist",
  "url": "http://yes.com",
  "likes": 109
}

###

GET http://localhost:3003/api/blogs